/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercise9;

/**
 *
 * @author shols
 */
public class exercise9GUI extends javax.swing.JFrame {

    /**
     * Creates new form exercise9GUI
     */
    public exercise9GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        f2cField = new javax.swing.JTextField();
        c2fField = new javax.swing.JTextField();
        celsiusLabel = new javax.swing.JLabel();
        c2fConvert = new javax.swing.JButton();
        fLabel = new javax.swing.JLabel();
        c2kField = new javax.swing.JTextField();
        c2kLabel = new javax.swing.JLabel();
        c2kConvert = new javax.swing.JButton();
        kelLabel = new javax.swing.JLabel();
        fLabel2 = new javax.swing.JLabel();
        celLabel2 = new javax.swing.JLabel();
        fah2celField = new javax.swing.JTextField();
        f2cConvert = new javax.swing.JButton();
        f2kField = new javax.swing.JTextField();
        f2kConvert = new javax.swing.JButton();
        fLabel3 = new javax.swing.JLabel();
        kelLabel2 = new javax.swing.JLabel();
        k2cField = new javax.swing.JTextField();
        k2cConvert = new javax.swing.JButton();
        kelLabel3 = new javax.swing.JLabel();
        celLabel3 = new javax.swing.JLabel();
        k2fConvert = new javax.swing.JButton();
        k2fField = new javax.swing.JTextField();
        kelLabel4 = new javax.swing.JLabel();
        fLabel4 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        f2cField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2cFieldActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temp Converter");

        celsiusLabel.setText("Celsius");

        c2fConvert.setText("Convert");
        c2fConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2fConvertActionPerformed(evt);
            }
        });

        fLabel.setText("Fahrenheit");

        c2kLabel.setText("Celsius");

        c2kConvert.setText("Convert");
        c2kConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2kConvertActionPerformed(evt);
            }
        });

        kelLabel.setText("Kelvin");

        fLabel2.setText("Fahrenheit");

        celLabel2.setText("Celsius");

        f2cConvert.setText("Convert");
        f2cConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2cConvertActionPerformed(evt);
            }
        });

        f2kConvert.setText("Convert");
        f2kConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2kConvertActionPerformed(evt);
            }
        });

        fLabel3.setText("Fahrenheit");

        kelLabel2.setText("Kelvin");

        k2cConvert.setText("Convert");
        k2cConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k2cConvertActionPerformed(evt);
            }
        });

        kelLabel3.setText("Kelvin");

        celLabel3.setText("Celsius");

        k2fConvert.setText("Convert");
        k2fConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k2fConvertActionPerformed(evt);
            }
        });

        kelLabel4.setText("Kelvin");

        fLabel4.setText("Fahrenheit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(c2kField)
                                        .addComponent(c2fConvert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(c2fField, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(c2kLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(celsiusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(c2kConvert)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(k2cField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kelLabel3)))
                        .addGap(192, 211, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(k2cConvert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(celLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(k2fField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kelLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(k2fConvert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fah2celField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(f2cConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(celLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(f2kField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(f2kConvert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kelLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c2fField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celsiusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c2fConvert)
                    .addComponent(fLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c2kField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2kLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c2kConvert)
                    .addComponent(kelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(k2cField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(k2cConvert)
                    .addComponent(celLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(k2fField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(k2fConvert)
                    .addComponent(fLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fah2celField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f2cConvert)
                    .addComponent(celLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f2kField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f2kConvert)
                    .addComponent(kelLabel2))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c2fConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2fConvertActionPerformed
        Ex9Converter temp = new Ex9Converter();
        double tempCel = (double)((Double.parseDouble(c2fField.getText())));
        double result = temp.c2f(tempCel);
        fLabel.setText(result + " Fahrenheit");
    }//GEN-LAST:event_c2fConvertActionPerformed

    private void c2kConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2kConvertActionPerformed
        Ex9Converter temp = new Ex9Converter();
        double tempCel = (double)((Double.parseDouble(c2kField.getText())));
        double result = temp.c2k(tempCel);
        kelLabel.setText(result + " Kelvin");
    }//GEN-LAST:event_c2kConvertActionPerformed

    private void f2cFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2cFieldActionPerformed
        
    }//GEN-LAST:event_f2cFieldActionPerformed

    private void f2kConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2kConvertActionPerformed
        Ex9Converter temp = new Ex9Converter();
        double tempF = (double)((Double.parseDouble(f2kField.getText())));
        double result = temp.f2k(tempF);
        kelLabel2.setText(String.format("%.2f Kelvin", result));
    }//GEN-LAST:event_f2kConvertActionPerformed

    private void k2cConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k2cConvertActionPerformed
        Ex9Converter temp = new Ex9Converter();
        double tempK = (double)((Double.parseDouble(k2cField.getText())));
        if(tempK >= 0){
            double result = temp.k2c(tempK);
            celLabel3.setText(result + " Celsius");
        }
        else{
            celLabel3.setText("Kelvin must be greater than 0");
        }
        
    }//GEN-LAST:event_k2cConvertActionPerformed

    private void k2fConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k2fConvertActionPerformed
        Ex9Converter temp = new Ex9Converter();
        double tempk = (double)((Double.parseDouble(k2fField.getText())));
        if(tempk >= 0){
            double result = temp.k2f(tempk);
            fLabel4.setText(result + " Fahrenheit");
        }
        else{
            fLabel4.setText("Kelvin must be greater than 0");
        }
        
    }//GEN-LAST:event_k2fConvertActionPerformed

    private void f2cConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2cConvertActionPerformed
        Ex9Converter temp = new Ex9Converter();
        double tempF = (double)((Double.parseDouble(fah2celField.getText())));
        double result = temp.f2c(tempF);
        celLabel2.setText(String.format("%.2f Celsius", result));
    }//GEN-LAST:event_f2cConvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exercise9GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exercise9GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exercise9GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exercise9GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exercise9GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c2fConvert;
    private javax.swing.JTextField c2fField;
    private javax.swing.JButton c2kConvert;
    private javax.swing.JTextField c2kField;
    private javax.swing.JLabel c2kLabel;
    private javax.swing.JLabel celLabel2;
    private javax.swing.JLabel celLabel3;
    private javax.swing.JLabel celsiusLabel;
    private javax.swing.JButton f2cConvert;
    private javax.swing.JTextField f2cField;
    private javax.swing.JButton f2kConvert;
    private javax.swing.JTextField f2kField;
    private javax.swing.JLabel fLabel;
    private javax.swing.JLabel fLabel2;
    private javax.swing.JLabel fLabel3;
    private javax.swing.JLabel fLabel4;
    private javax.swing.JTextField fah2celField;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton k2cConvert;
    private javax.swing.JTextField k2cField;
    private javax.swing.JButton k2fConvert;
    private javax.swing.JTextField k2fField;
    private javax.swing.JLabel kelLabel;
    private javax.swing.JLabel kelLabel2;
    private javax.swing.JLabel kelLabel3;
    private javax.swing.JLabel kelLabel4;
    // End of variables declaration//GEN-END:variables
}
